[tool.poetry]
name = "iamra"
version = "0.5.0"
description = "IAM Roles Anywhere credentials helper"
authors = ["Gavin Adams <me@gavinadams.org>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/gadams999/iamra"
repository = "https://github.com/gadams999/iamra"
documentation = "https://iamra.readthedocs.io"
classifiers = [
    "Development Status :: 1 - Planning",
]

[tool.poetry.urls]
Changelog = "https://github.com/gadams999/iamra/releases"

[tool.poetry.dependencies]
python = "^3.9"
cryptography = "^39.0.0"
urllib3 = "^1.26.13"
requests = "^2.28.1"
boto3 = "^1.26.50"

# [tool.poetry.scripts]
# iamra = "iamra.__main__:main"

[tool.poetry.dev-dependencies]
# [tool.poetry.group.dev.dependencies]
Pygments = ">=2.10.0"
black = ">=21.10b0"
coverage = {extras = ["toml"], version = ">=6.2"}
darglint = ">=1.8.1"
flake8 = ">=4.0.1"
flake8-bandit = ">=2.1.2"
flake8-bugbear = ">=21.9.2"
flake8-docstrings = ">=1.6.0"
flake8-rst-docstrings = ">=0.2.5"
furo = ">=2021.11.12"
isort = ">=5.10.1"
mypy = ">=0.930"
pep8-naming = ">=0.12.1"
pre-commit = ">=2.16.0"
pre-commit-hooks = ">=4.1.0"
pytest = ">=6.2.5"
pyupgrade = ">=2.29.1"
safety = ">=1.10.3"
sphinx = ">=4.3.2"
sphinx-autobuild = ">=2021.3.14"
sphinx-click = ">=3.0.2"
typeguard = ">=2.13.3"
xdoctest = {extras = ["colors"], version = ">=0.15.10"}
myst-parser = {version = ">=0.16.1"}
types-requests = "^2.28.11.7"
requests-mock = "^1.10.0"

[tool.poetry.group.dev.dependencies]
types-python-dateutil = "^2.8.19.5"
types-boto3 = "^1.0.2"
types-botocore = "^1.0.2"
boto3-stubs = {extras = ["boto3"], version = "^1.26.50"}

[tool.coverage.paths]
source = ["src", "*/site-packages"]
tests = ["tests", "*/tests"]

[tool.coverage.run]
branch = true
source = ["iamra", "tests"]

[tool.coverage.report]
show_missing = true
fail_under = 100

[tool.isort]
profile = "black"
force_single_line = true
lines_after_imports = 2

[tool.mypy]
strict = true
warn_unreachable = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
